pragma Singleton

import Quickshell

// Material Design glyphs from Symbols Nerd Font.
Singleton {
    function g(cp: int): string {
        return String.fromCodePoint(cp);
    }

    readonly property string wifi: g(0xf05a9)
    readonly property string wifiOff: g(0xf05aa)
    readonly property string wifiLock: g(0xf16bf)
    readonly property string wifiStrength1: g(0xf091f)
    readonly property string wifiStrength2: g(0xf0922)
    readonly property string wifiStrength3: g(0xf0925)
    readonly property string wifiStrength4: g(0xf0928)
    readonly property string bluetooth: g(0xf00af)
    readonly property string bluetoothOff: g(0xf00b2)
    readonly property string focus: g(0xf0377)
    readonly property string gameMode: g(0xf0297)
    readonly property string lock: g(0xf0341)
    readonly property string lockFilled: g(0xf033e)
    readonly property string sleep: g(0xf0f65)
    readonly property string nightLight: g(0xf0f65)
    readonly property string volumeHigh: g(0xf057e)
    readonly property string volumeMedium: g(0xf0580)
    readonly property string volumeLow: g(0xf057f)
    readonly property string volumeOff: g(0xf0581)
    readonly property string microphone: g(0xf036c)
    readonly property string monitor: g(0xf0379)
    readonly property string headphones: g(0xf02cb)
    readonly property string mouse: g(0xf037d)
    readonly property string phone: g(0xf011c)
    readonly property string brightness: g(0xf05a8)
    readonly property string keyboard: g(0xf030c)
    readonly property string chevronRight: g(0xf0142)
    readonly property string chevronLeft: g(0xf0141)
    readonly property string arrowLeft: g(0xf004d)
    readonly property string arrowRight: g(0xf0054)
    readonly property string close: g(0xf0156)
    readonly property string play: g(0xf040a)
    readonly property string pause: g(0xf03e4)
    readonly property string previous: g(0xf04ae)
    readonly property string next: g(0xf04ad)
    readonly property string music: g(0xf0387)
    readonly property string check: g(0xf012c)
    readonly property string logout: g(0xf0343)
    readonly property string reboot: g(0xf0709)
    readonly property string power: g(0xf0425)
    readonly property string search: g(0xf0349)
    readonly property string account: g(0xf0004)
    readonly property string battery: g(0xf0079)
    readonly property string batteryCharging: g(0xf0084)
    readonly property string batteryHalf: g(0xf007e)
    readonly property string tune: g(0xf066a)
    readonly property string plus: g(0xf0415)
    readonly property string minus: g(0xf0374)
    readonly property string app: g(0xf08c6)
    readonly property string cog: g(0xf0493)
    readonly property string bell: g(0xf009a)
    readonly property string clock: g(0xf0150)
    readonly property string palette: g(0xf03d8)
    readonly property string motion: g(0xf05d8)
    readonly property string rocket: g(0xf14de)
    readonly property string dashboard: g(0xf0a1d)
    readonly property string island: g(0xf1513)
    readonly property string shieldLock: g(0xf0ccc)
    readonly property string info: g(0xf02fd)
    readonly property string drag: g(0xf01db)
    readonly property string weatherSunny: g(0xf0599)
    readonly property string weatherPartlyCloudy: g(0xf0595)
    readonly property string weatherCloudy: g(0xf0590)
    readonly property string weatherFog: g(0xf0591)
    readonly property string weatherRainy: g(0xf0597)
    readonly property string weatherPouring: g(0xf0596)
    readonly property string weatherSnowy: g(0xf0598)
    readonly property string weatherStorm: g(0xf067e)
    readonly property string leaf: g(0xf032a)
    readonly property string balance: g(0xf05d1)
    readonly property string speedometer: g(0xf04c5)
    readonly property string chip: g(0xf035b)
    readonly property string memory: g(0xefc5)
}
